import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')
  const [email, setEmail] = useState('')
  const [subject, setSubject] = useState('')
  const [message, setMessage] = useState('')
  const [filename, setFileName] = useState(null)
  const [file, setFile] = useState(null)
  const [submitted, setSubmitted] = useState(false)

  const handleSubmit = (e) => {

    if (firstName == '') {
      alert("empty first name")
      return
    }
    if (lastName == '') {
      alert("empty last name")
      return
    }
    if (email == '') {
      alert("empty email")
      return
    }
    if (subject == '') {
      alert("empty subject")
      return
    }
    if (message == '') {
      alert("empty message")
      return
    }
    if (!email.includes("@")) {
      alert("invalid email")
      return
    }

    e.preventDefault()
    console.log("e.target.files = " + e.target.files)
    console.log('Sending')
    let data = {
      firstName,
      lastName,
      email,
      subject,
      message,
      filename,
    }

    const formData = new FormData();

		formData.append('File', file);

    fetch('/api/contact', {
      method: 'POST',
      body: formData,
      // headers: {
      //   'Accept': 'application/json, text/plain, */*',
      //   'Content-Type': 'application/json'
      // },
      // body: JSON.stringify(data) + formData 
    }).then((res) => {
      console.log('Response received')
      if (res.status === 200) {
        console.log('Response succeeded!')
        setSubmitted(true)
        // setFirstName('')
        // setLastName('')
        // setEmail('')
        // setSubject('')
        // setMessage('')
        // setFiles('')
      }
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>

        <div className={styles.container}>

          < form className={styles.contactForm} encType="multipart/form-data">
            < formGroup className={styles.inputGroup} >
              < label htmlFor='first name'>First name</label>
              < input type='text' name='name' className={styles.inputField} onChange={(e) => { setFirstName(e.target.value) }} placeholder="your  first name" />
            </formGroup>
            < formGroup className={styles.inputGroup} >
              < label htmlFor='last name'>Last name</label>
              < input type='text' name='name' className={styles.inputField} onChange={(e) => { setLastName(e.target.value) }} placeholder="your last name" />
            </formGroup>
            < formGroup className={styles.inputGroup} >
              < label htmlFor='email'>Email</label>
              < input type='email' name='email' className={styles.inputField} onChange={(e) => { setEmail(e.target.value) }} placeholder="your email" />
            </formGroup>
            < formGroup className={styles.inputGroup} >
              < label htmlFor='message'>Subject</label>
              < input type='text' name='message' className={styles.inputField} onChange={(e) => { setSubject(e.target.value) }} placeholder="subject" />
            </formGroup>
            < formGroup className={styles.inputGroup} >
              < label htmlFor='message'>Message</label>
              < input type='text' name='message' className={styles.inputField} onChange={(e) => { setMessage(e.target.value) }} placeholder="your message" />
            </formGroup>
            < formGroup className={styles.inputGroup} >
              <label>Pièces jointes: </label>
              <input type="file" name="file[]" multiple={true} onChange={(e) => {
                console.log(e.target.files[0])
                setFileName(e.target.files[0].name)
                setFile(e.target.files[0])
              }} />
            </formGroup>

            < input type='submit' onClick={(e) => { handleSubmit(e) }} />
            {filename == '' ? null : <img src={filename} alt="images" width={100 + 'px'} height={100 + 'px'}></img>}
          </form >

        </div>

      </main>
    </>
  )
}